apiVersion: v1
kind: Pod
metadata:
    name: web-app-pod
    labels:
        type: app
spec:
    containers:
        - name: web-app
          image: image_tag
          ports:
          - containerPort: 8080
