apiVersion: v1
kind: Pod
metadata:
    name: pod-name
    labels:
        type: app
spec:
    containers:
        - name: app-con
          image: image-tag
          ports:
          - containerPort: 8080
